import './globals.css'
import ChatwoptWidget from './components/ChatWoot'
import { Manrope } from 'next/font/google'
import FooterBar from './components/FooterBar'

const inter = Manrope({ 
  subsets: ['latin'],
  weight:['400']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ChatwoptWidget/>
        </body>
     

    </html>
  )
}
